#include "network/remote_client.h"
#include "security/credential_store.h"
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QNetworkReply>
#include <QCryptographicHash>
#include <QSslCertificate>
#include <QSslError>

RemoteClient::RemoteClient(QObject*p):QObject(p){}
void RemoteClient::configure(QUrl endpoint,QString credential){endpoint_=std::move(endpoint);credentialName_=std::move(credential);std::string value,error;if(CredentialStore::load(credentialName_.toStdString(),value,error))token_=QByteArray::fromStdString(value);}
void RemoteClient::protectReply(QNetworkReply *reply){connect(reply,&QNetworkReply::sslErrors,this,[this,reply](const QList<QSslError>&errors){bool onlySelfSigned=!errors.isEmpty();for(const auto&e:errors)if(e.error()!=QSslError::SelfSignedCertificate&&e.error()!=QSslError::SelfSignedCertificateInChain&&e.error()!=QSslError::UnableToGetLocalIssuerCertificate)onlySelfSigned=false;if(!onlySelfSigned)return;const auto certificate=reply->sslConfiguration().peerCertificate();if(certificate.isNull())return;const QString fingerprint=QString::fromLatin1(certificate.digest(QCryptographicHash::Sha256).toHex(':')).toUpper();const std::string trustKey=(credentialName_+"/certificate").toStdString();std::string trusted,error;if(CredentialStore::load(trustKey,trusted,error)&&QString::fromStdString(trusted)==fingerprint){reply->ignoreSslErrors(errors);return;}if(trusted.empty()&&certificatePrompt_&&certificatePrompt_(endpoint_.toString(),fingerprint)){CredentialStore::save(trustKey,fingerprint.toStdString(),error);reply->ignoreSslErrors(errors);}});}
QNetworkRequest RemoteClient::request(const QString&path)const{QUrl url=endpoint_;url.setPath("/api/v1/"+path);QNetworkRequest r(url);r.setHeader(QNetworkRequest::ContentTypeHeader,"application/json");if(!token_.isEmpty())r.setRawHeader("Authorization","Bearer "+token_);return r;}
void RemoteClient::postCredentials(const QString&path,const QString&user,const QString&password,std::function<void(bool,QString)>done,bool save){QJsonObject o{{"username",user},{"password",password}};auto*reply=network_.post(request(path),QJsonDocument(o).toJson(QJsonDocument::Compact));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{QJsonObject result=QJsonDocument::fromJson(reply->readAll()).object();bool ok=reply->error()==QNetworkReply::NoError;if(ok&&save){token_=result["token"].toString().toLatin1();std::string e;CredentialStore::save(credentialName_.toStdString(),token_.toStdString(),e);}done(ok,ok?QString():result["error"].toString(reply->errorString()));reply->deleteLater();});}
void RemoteClient::registerUser(const QString&u,const QString&p,std::function<void(bool,QString)>d){postCredentials("register",u,p,std::move(d),false);}void RemoteClient::login(const QString&u,const QString&p,std::function<void(bool,QString)>d){postCredentials("login",u,p,std::move(d),true);}
void RemoteClient::logout(std::function<void(bool,QString)>done){auto*reply=network_.post(request("logout"),QByteArray{});protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{bool ok=reply->error()==QNetworkReply::NoError;if(ok){token_.clear();std::string error;CredentialStore::remove(credentialName_.toStdString(),error);}done(ok,ok?QString():reply->errorString());reply->deleteLater();});}
void RemoteClient::status(std::function<void(QJsonObject,QString)>done){auto*reply=network_.get(request("status"));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{auto object=QJsonDocument::fromJson(reply->readAll()).object();done(object,reply->error()==QNetworkReply::NoError?QString():object["error"].toString(reply->errorString()));reply->deleteLater();});}
void RemoteClient::checkChunks(const QStringList&hashes,std::function<void(QStringList,QString)>done){QJsonArray a;for(auto&s:hashes)a.append(s);auto*reply=network_.post(request("chunks/check"),QJsonDocument(QJsonObject{{"hashes",a}}).toJson(QJsonDocument::Compact));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{QJsonObject o=QJsonDocument::fromJson(reply->readAll()).object();QStringList missing;for(auto v:o["missing"].toArray())missing<<v.toString();done(missing,reply->error()==QNetworkReply::NoError?QString():o["error"].toString(reply->errorString()));reply->deleteLater();});}
void RemoteClient::uploadChunk(const QString&id,const QByteArray&data,std::function<void(bool,QString)>done){QNetworkRequest r=request("chunks/"+id);r.setHeader(QNetworkRequest::ContentTypeHeader,"application/octet-stream");auto*reply=network_.put(r,data);protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{bool ok=reply->error()==QNetworkReply::NoError;done(ok,ok?QString():reply->errorString());reply->deleteLater();});}
void RemoteClient::downloadChunk(const QString&id,std::function<void(QByteArray,QString)>done){auto*reply=network_.get(request("chunks/"+id));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{QByteArray data=reply->readAll();done(reply->error()==QNetworkReply::NoError?data:QByteArray{},reply->error()==QNetworkReply::NoError?QString():reply->errorString());reply->deleteLater();});}
void RemoteClient::commitSnapshot(const QJsonObject&manifest,std::function<void(bool,QString)>done){auto*reply=network_.post(request("snapshots"),QJsonDocument(manifest).toJson(QJsonDocument::Compact));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{bool ok=reply->error()==QNetworkReply::NoError;done(ok,ok?QString():reply->errorString());reply->deleteLater();});}
void RemoteClient::deleteSnapshot(const QString&id,std::function<void(bool,QString)>done){auto*reply=network_.deleteResource(request("snapshots/"+id));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{bool ok=reply->error()==QNetworkReply::NoError;done(ok,ok?QString():reply->errorString());reply->deleteLater();});}
void RemoteClient::listSnapshots(std::function<void(QJsonArray,QString)>done){auto*reply=network_.get(request("snapshots"));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{QJsonObject o=QJsonDocument::fromJson(reply->readAll()).object();done(o["snapshots"].toArray(),reply->error()==QNetworkReply::NoError?QString():o["error"].toString(reply->errorString()));reply->deleteLater();});}
void RemoteClient::getSnapshot(const QString&id,std::function<void(QJsonObject,QString)>done){auto*reply=network_.get(request("snapshots/"+id));protectReply(reply);connect(reply,&QNetworkReply::finished,this,[=]{auto object=QJsonDocument::fromJson(reply->readAll()).object();done(object,reply->error()==QNetworkReply::NoError?QString():object["error"].toString(reply->errorString()));reply->deleteLater();});}
