#include "automation/job_manager.h"
#include "automation/cron.h"
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QStandardPaths>
#include <QDir>
#include <QFile>
#include <QUuid>

namespace { QString filePath(){QString dir=QStandardPaths::writableLocation(QStandardPaths::AppDataLocation);QDir().mkpath(dir);return dir+"/jobs.json";} }
JobManager::JobManager(QObject*p):QObject(p){connect(&timer_,&QTimer::timeout,this,[this]{tick();});load();}
void JobManager::start(){timer_.start(30000);syncWatchers();tick();}void JobManager::pause(bool value){paused_=value;}
bool JobManager::upsert(BackupJob job,QString&error){CronExpression expression;std::string detail;if(!expression.parse(job.cron.toStdString(),detail)){error=QString::fromStdString(detail);return false;}if(job.sources.isEmpty()||job.destination.isEmpty()){error=tr("来源和仓库不能为空");return false;}if(job.id.isEmpty())job.id=QUuid::createUuid().toString(QUuid::WithoutBraces);updateNext(job);for(auto&existing:jobs_)if(existing.id==job.id){existing=job;save();syncWatchers();return true;}jobs_.append(job);save();syncWatchers();return true;}
bool JobManager::remove(const QString&id,QString&error){for(int i=0;i<jobs_.size();++i)if(jobs_[i].id==id){jobs_.removeAt(i);save();syncWatchers();return true;}error=tr("任务不存在");return false;}
void JobManager::updateNext(BackupJob&job){CronExpression c;std::string e;if(c.parse(job.cron.toStdString(),e)){auto next=c.next(QDateTime::currentSecsSinceEpoch());if(next!=-1)job.nextRun=QDateTime::fromSecsSinceEpoch(next);}}
void JobManager::requestRun(const BackupJob&job){if(paused_||!executor_)return;if(running_.contains(job.id)){pending_.insert(job.id);return;}running_.insert(job.id);executor_(job);}
void JobManager::tick(){if(paused_||!executor_)return;QDateTime now=QDateTime::currentDateTime();for(auto&job:jobs_)if(job.enabled&&job.nextRun.isValid()&&job.nextRun<=now){job.nextRun=QDateTime();requestRun(job);updateNext(job);}save();}
void JobManager::syncWatchers(){watchers_.clear();for(const auto&job:jobs_){if(!job.enabled||!job.realtime)continue;for(const QString&source:job.sources){std::string key=(job.id+"|"+source).toStdString();QString sourcePath=QDir::cleanPath(source),destination=QDir::cleanPath(job.destination),excluded;if(destination.startsWith(sourcePath+"/",Qt::CaseInsensitive)||destination.startsWith(sourcePath+"\\",Qt::CaseInsensitive))excluded=QDir(sourcePath).relativeFilePath(destination).replace('\\','/');auto watcher=std::make_unique<DirectoryWatcher>();std::string error;watcher->start(source.toUtf8().toStdString(),[this,id=job.id,key,excluded](const std::vector<std::string>&paths,bool){if(!excluded.isEmpty()&&!paths.empty()){bool onlyOutput=true;for(auto&p:paths){QString changed=QString::fromUtf8(p.c_str()).replace('\\','/');if(!changed.startsWith(excluded+"/")&&changed!=excluded){onlyOutput=false;break;}}if(onlyOutput)return;}QMetaObject::invokeMethod(this,[this,id,key]{int generation=++realtimeGeneration_[key];if(!realtimeFirst_[key].isValid()){realtimeFirst_[key]=QDateTime::currentDateTime();QDateTime first=realtimeFirst_[key];QTimer::singleShot(30000,this,[this,id,key,first]{if(paused_||realtimeFirst_[key]!=first||!executor_)return;realtimeFirst_[key]=QDateTime();++realtimeGeneration_[key];for(const auto&job:jobs_)if(job.id==id&&job.enabled){requestRun(job);break;}});}QTimer::singleShot(3000,this,[this,id,key,generation]{if(paused_||realtimeGeneration_[key]!=generation||!executor_)return;realtimeFirst_[key]=QDateTime();for(const auto&job:jobs_)if(job.id==id&&job.enabled){requestRun(job);break;}});},Qt::QueuedConnection);},error);if(watcher->running())watchers_[key]=std::move(watcher);}}
}
void JobManager::markFinished(const QString&id,bool success,const QString&message){running_.remove(id);BackupJob rerun;bool shouldRerun=pending_.remove(id)>0;for(auto&job:jobs_)if(job.id==id){job.lastRun=QDateTime::currentDateTime();job.lastResult=(success?tr("成功："):tr("失败："))+message;updateNext(job);rerun=job;break;}save();if(shouldRerun)requestRun(rerun);}
void JobManager::save(){QJsonArray array;for(const auto&j:jobs_){QJsonObject filter{{"pathContains",QString::fromUtf8(j.filter.pathContains.c_str())},{"nameContains",QString::fromUtf8(j.filter.nameContains.c_str())},{"extension",QString::fromUtf8(j.filter.extension.c_str())},{"ownerContains",QString::fromUtf8(j.filter.ownerContains.c_str())},{"type",static_cast<int>(j.filter.type)},{"minSize",static_cast<double>(j.filter.minSize)},{"maxSize",static_cast<double>(j.filter.maxSize)},{"afterMtimeMs",static_cast<double>(j.filter.afterMtimeMs)},{"beforeMtimeMs",static_cast<double>(j.filter.beforeMtimeMs)}};QJsonArray extensions;for(const auto&s:j.filter.extensions)extensions.append(QString::fromUtf8(s.c_str()));filter["extensions"]=extensions;QJsonArray rules;for(const auto&r:j.filter.pathRules)rules.append(QJsonObject{{"include",r.include},{"pattern",QString::fromUtf8(r.pattern.c_str())}});filter["pathRules"]=rules;QJsonObject o{{"id",j.id},{"name",j.name},{"destination",j.destination},{"cron",j.cron},{"repositoryType",j.repositoryType},{"backupMode",j.backupMode},{"remoteProfile",j.remoteProfile},{"compressionLevel",j.compressionLevel},{"filter",filter},{"enabled",j.enabled},{"realtime",j.realtime},{"retention",j.retention},{"lastRun",j.lastRun.toString(Qt::ISODateWithMs)},{"nextRun",j.nextRun.toString(Qt::ISODateWithMs)},{"lastResult",j.lastResult}};QJsonArray sources;for(auto&s:j.sources)sources.append(s);o["sources"]=sources;array.append(o);}QSaveFile f(filePath());if(f.open(QIODevice::WriteOnly)){f.write(QJsonDocument(QJsonObject{{"version",2},{"jobs",array}}).toJson());f.commit();}}
void JobManager::load(){QFile f(filePath());if(!f.open(QIODevice::ReadOnly))return;QJsonDocument d=QJsonDocument::fromJson(f.readAll());for(auto value:d.object()["jobs"].toArray()){auto o=value.toObject();BackupJob j;j.id=o["id"].toString();j.name=o["name"].toString();j.destination=o["destination"].toString();j.cron=o["cron"].toString();j.repositoryType=o["repositoryType"].toString("local");j.backupMode=o["backupMode"].toString("incremental");j.remoteProfile=o["remoteProfile"].toString();j.compressionLevel=o["compressionLevel"].toInt(6);auto filter=o["filter"].toObject();j.filter.pathContains=filter["pathContains"].toString().toUtf8().toStdString();j.filter.nameContains=filter["nameContains"].toString().toUtf8().toStdString();j.filter.extension=filter["extension"].toString().toUtf8().toStdString();j.filter.ownerContains=filter["ownerContains"].toString().toUtf8().toStdString();j.filter.type=static_cast<EntryTypeFilter>(filter["type"].toInt());j.filter.minSize=static_cast<uint64_t>(filter["minSize"].toDouble());j.filter.maxSize=static_cast<uint64_t>(filter["maxSize"].toDouble());j.filter.afterMtimeMs=static_cast<int64_t>(filter["afterMtimeMs"].toDouble());j.filter.beforeMtimeMs=static_cast<int64_t>(filter["beforeMtimeMs"].toDouble());for(auto extension:filter["extensions"].toArray())j.filter.extensions.push_back(extension.toString().toUtf8().toStdString());for(auto value:filter["pathRules"].toArray()){auto rule=value.toObject();j.filter.pathRules.push_back({rule["include"].toBool(),rule["pattern"].toString().toUtf8().toStdString()});}j.enabled=o["enabled"].toBool(true);j.realtime=o["realtime"].toBool();j.retention=o["retention"].toInt(3);j.lastRun=QDateTime::fromString(o["lastRun"].toString(),Qt::ISODateWithMs);j.lastResult=o["lastResult"].toString();for(auto s:o["sources"].toArray())j.sources<<s.toString();updateNext(j);jobs_<<j;}}
